services:
  vultr:
    image: vultr-manager:latest
    restart: always
    ports:
      - "8087:8087"
    environment:
      API: apikey
      PASSWORD: password
      PORT: 8080
      DATABASE_ADDR: localhost
      DATABASE_USER: vultr
      DATABASE_PASSWORD: vultr
      DATABASE_SCHEMA: vultr
      SYNC_DATABASE: true
