services:
  vultr:
    image: vultr-manager:latest
    restart: always
    ports:
      - "8087:8087"
    environment:
      API: "1234"
      PORT: 8087
      PASSWORD: 1234
      DATABASE_ADDR: localhost:5432
      DATABASE_USER: root
      DATABASE_PASSWORD: "1234"
      DATABASE_SCHEMA: vultrmanager
